openai:
  model: gpt-4o
  temperature: 0.0
anthropic:
  model: claude-3-5-sonnet-20241022
  temperature: 0.0
ollama:
  llama3:
    model: llama3
    temperature: 0.0
  mistral:
    model: mistral
    temperature: 0.0
